### ISSUE TITLE
questions about train_val.prototxt

### ISSUE THREAD

**Issue by xiaomr** [farmingyard/ShuffleNet#12]
hi @farmingyard ,  Thanks for sharing your code!

I change your deploy prototxt for train_val prototxt,  when I implement sufflenet on imagenet12, I can't get the accuracy as discussed,   I didn't add lr_mult and decay_mult for conv layers,  set them to 0 as your deploy prototxt,  could it have influence on the result ?

expect your advice, 3Q~

**Comment by farmingyard** [comment]
@xiaomr 
You should add loss and accuracy layers, just like below:
layer {
  name: "loss"
  type: "SoftmaxWithLoss"
  bottom: "ip1"
  bottom: "label"
  top: "loss"
}
layer {
  name: "accuracy_top1"
  type: "Accuracy"
  bottom: "ip1"
  bottom: "label"
  top: "accuracy_top1"
  include {
    phase: TEST
  }
}
layer {
  name: "accuracy_top5"
  type: "Accuracy"
  bottom: "ip1"
  bottom: "label"
  top: "accuracy_top5"
  include {
    phase: TEST
  }
  accuracy_param {
    top_k: 5
  }
}

**Comment by xiaomr** [comment]
@farmingyard  it works,  thanks!
