### ISSUE TITLE
Some questions about output channels.

### ISSUE THREAD

**Issue by KeyKy** [farmingyard/ShuffleNet#2]
why is the num output of resx1_conv1 not 60?
why is the num output of resx1_conv3 not 240?
why is the num output of resx5_conv1 not 120?
why is the num output of resx5_conv3 not 480?
why is the num output of resx13_conv1 not 240?
why is the num output of resx13_conv3 not 960?

Thanks!

**Comment by farmingyard** [comment]
@KeyKy Because in ShuffleNet's bottleneck, when the stride=2, the combination process is concat but not elewise, so take resx1 for example, the output 240=24+216, am i clear?

**Comment by KeyKy** [comment]
Ho. i see!
