### ISSUE TITLE
Problem with Reshape

### ISSUE THREAD

**Issue by xuzijian** [farmingyard/ShuffleNet#6]
@farmingyard 
Thanks a lot for sharing the 'shuffle' layer as well as dw-convolution layer ;-). But I guess there is a slight bug that you have not implement reshape function. I have encountered strange behavior when I inputted an image with another shape and I found such problem. What I did is just add following code in my cpp file and it worked fine.

template \<typename Dtype\>
void ShuffleChannelLayer<Dtype>::Reshape(const vector<Blob<Dtype>*>& bottom, const vector<Blob<Dtype>*>& top) {
  top[0]->ReshapeLike(*bottom[0]);
}

Thanks again for lots of useful sharing.
Zijian

**Comment by farmingyard** [comment]
@xuzijian 
yeah，you are right，but i didn't encounted the related crash. Thanks！
