### ISSUE TITLE
Unknown layer type: ConvolutionDepthwise

### ISSUE THREAD

**Issue by HandsomeHans** [farmingyard/ShuffleNet#7]
when i run a demo, i face this problem.
i have put .cpp .cu and .hpp right in the dir, and modified caffe.proto.
also gone well when make, make test and make runtest

**Comment by HandsomeHans** [comment]
Maybe change 'ConvolutionDepthwise' to 'ChannelShuffle' in prototxt
I will try it right now

**Comment by HandsomeHans** [comment]
OK, I solved this problem by change all 'ConvolutionDepthwise' to 'Convolution'. 
However, a new problem came outm "Source param shape is 54 1 3 3 (486); target param shape is 54 54 3 3 (26244)" 
I downloaded ur caffemodel, and want to do finetune on my dataset.

**Comment by farmingyard** [comment]
@HandsomeHans 
You can use 'ConvolutionDepthwise' layer from this repository: https://github.com/farmingyard/caffe-mobilenet

**Comment by HandsomeHans** [comment]
@farmingyard Thank you very much

**Comment by HandsomeHans** [comment]
Problem again.

```
I0728 13:49:20.766363  3003 upgrade_proto.cpp:77] Attempting to upgrade batch norm layers using deprecated params: shufflenet_1x_g3.caffemodel
I0728 13:49:20.766400  3003 upgrade_proto.cpp:80] Successfully upgraded batch norm layers using deprecated params.
F0728 13:49:20.766446  3003 net.cpp:750] Check failed: target_blobs.size() == source_layer.blobs_size() (0 vs. 1) Incompatible number of blobs for layer resx1_conv2
*** Check failure stack trace: ***
    @     0x7fee7f5c47fa  google::LogMessage::Fail()
    @     0x7fee7f5c4754  google::LogMessage::SendToLog()
    @     0x7fee7f5c4104  google::LogMessage::Flush()
    @     0x7fee7f5c720b  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fee8667aa36  caffe::Net<>::CopyTrainedLayersFrom()
    @     0x7fee8667aaaa  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7fee8667ab76  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x40c50b  CopyLayers()
    @           0x40d3fe  train()
    @           0x40b48f  main
    @       0x314aa1f84d  (unknown)
    @           0x40aec9  (unknown)

```

I think this might occur when copying param from ur caffemodel to mine.
